#cloud-config
users:
 - name: motorher
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
      - ssh-rsa
      

bootcmd:
  - echo '<p>vm id:' "$(hostname)" '</p><br><img src="https://storage.yandexcloud.net/bucket-for-kotishe-picture/silk.jpg?x=500&y=-500">' >  /var/www/html/index.html